map $http_x_forwarded_proto $forwarded_scheme {
    default $http_x_forwarded_proto;
    ""      $scheme;
}

server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    sub_filter_once off;
    sub_filter_types text/html text/css text/xml application/xml application/rss+xml application/javascript;
    sub_filter 'https://petewall.net/' '$forwarded_scheme://$http_host/';
    sub_filter 'https://petewall.net"' '$forwarded_scheme://$http_host"';

    location / {
        try_files $uri $uri/ =404;
    }
}
